#!/bin/sh
#
# rc file para SonarQube
#
# chkconfig: 345 96 10
# description: SonarQube (www.sonarsource.org)
#
### INICIO INIT INFO
# Provides: sonar
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: SonarQube (www.sonarsource.org)
# Description: SonarQube (www.sonarsource.org)
### FIM INIT INFO

/sonar/server/sonarqube-5.6/bin/linux-x86-64/sonar.sh start
